version: "3.2"
services:
  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://mongo-db:27017/
      ME_CONFIG_BASICAUTH: false

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "14330:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd!"
      ACCEPT_EULA: "Y"